# Workflow: Runs normal tests
# Tests compliation uses `-fsanitize=address`
# to display memory usage
# Triggered on push or pull request to main

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  normal-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make tests
    - name: run tests
      run: bin/protocol_tests


  sanitizer-tests:
    runs-on: ubuntu-latest
    needs: normal-tests
    strategy:
      fail-fast: false
      matrix:
        san: [asan, ubsan, tsan, lsan]

    steps:
      - uses: actions/checkout@v4

      - name: Build with sanitizer
        run: make clean && make tests SAN_PROFILE=${{ matrix.san }}

      - name: Run tests
        run: |
          if [ "${{ matrix.san }}" = "asan" ]; then
            ASAN_OPTIONS=detect_leaks=1:exitcode=42 ./bin/protocol_tests
          else
            ./bin/protocol_tests
          fi