# Workflow: Runs normal tests
# Tests compliation uses `-fsanitize=address`
# to display memory usage
# Triggered on push or pull request to main

name: Tests

on:
  push:
    branches: [ "main", "compat" ]
  pull_request:
    branches: [ "main" ]

jobs:
  server-compilation:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: build
      run: make server_build

  client-compilation:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: build
      run: make client_build

  sanitizer-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        san: [asan, ubsan, tsan, lsan]

    steps:
      - uses: actions/checkout@v5
      - name: make
        run: make tests
      - name: run tests with memory leaks error status
        run: ASAN_OPTIONS=detect_leaks=1:exitcode=42  ./bin/protocol_tests
      - uses: actions/checkout@v4

      - name: Build with sanitizer
        run: make clean && make tests SAN_PROFILE=${{ matrix.san }}

      - name: Run tests
        run: |
          if [ "${{ matrix.san }}" = "asan" ]; then
            ASAN_OPTIONS=detect_leaks=1:exitcode=42 ./bin/protocol_tests
          else
            ./bin/protocol_tests
          fi
